// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function Card(Props) {
  var state = Props.state;
  Props.value;
  var handleClick = Props.handleClick;
  if (state) {
    return React.createElement("div", {
                className: "card card-visible sprite sprite-5-5",
                onClick: (function (param) {
                    return Curry._1(handleClick, /* () */0);
                  })
              });
  } else {
    return React.createElement("div", {
                className: "card card-hidden",
                onClick: (function (param) {
                    return Curry._1(handleClick, /* () */0);
                  })
              });
  }
}

var make = Card;

exports.make = make;
/* react Not a pure module */
