// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Memory$MemoryGame = require("./Memory.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Memory$MemoryGame.make, { }), "app");

/*  Not a pure module */
