// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

function Memory(Props) {
  var cards = Belt_Array.map(Belt_Array.range(0, 15), (function (param) {
          return React.createElement("div", {
                      className: "card"
                    });
        }));
  return React.createElement("div", {
              className: "app"
            }, React.createElement("div", {
                  className: "board"
                }, cards));
}

var make = Memory;

exports.make = make;
/* react Not a pure module */
